
# simply just for testing, this is not seriously used
# :< | Most in accurate way to test code generation
module Loader
    class Template 
        def fill_simple_Template(x : String)
            tmpl = "HTML/main.html"
            File.open(tmpl, "w") do |f|
                f.print "<!-- This file was generated by the server, do not remove this file unless youa re a developer -->"
                f.print "<!DOCTYPE html>"
                f.print "<html lang='en'>"
                f.print "<head>"
                f.print "<meta charset='UTF-8'>" 
                f.print "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
                f.print "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                f.print "<title>Pre generated template</title>"
                f.print "</head>"
                f.print "<body>"
                f.print "<div>"
                f.print "<p> #{x} </p>"
                f.print "</div>"
                f.print "</body>"
                f.print "</html>"
            end
        end
    end
end